settings:
  #################   DATASET CONFIG   ###################

  trainloader:
    name: CLIPFeatureLoader
    args:
      root_dir: "/content/data/flickr30k_images/flickr30k_images"
      ann_path: "/content/data/train.json"
      model_name: "ViT-B/32"
      batch_size: 128

  valloader:
    name: CLIPFeatureLoader
    args:
      root_dir: "/content/data/flickr30k_images/flickr30k_images"
      ann_path: "/content/data/val.json"
      model_name: "ViT-B/32"
      batch_size: 128
      num_workers: 2

  #################   TRAINING CONFIG   ###################
  
  globals:
    gpu_devices: '0'                     # supports multi-gpus
    num_epochs: 100
    mixed_precision: False                # whether to use nvidia apex
    total_accumulate_steps: 0           # step * batch_size, not use if equal 0, gradient accumulation
  
  model:
    name: "CLIP"
    args:
      d_embed: 512                      # output_dim
      name: "ViT-B/32"


  loss:
    name: "contrastive"                # [contrastive, nxtent, custom_nxtent, triplet]
    # distance: 
    #   name: "cosine"                   # [cosine, dot, euclidean]      
    # reducer:
    #   name: "threshold"
    #   high: 0.2
    # regularizer:                     # [l1, l2, mean]
    #   name: "l2"
      
  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

