settings:
  #################   DATASET CONFIG   ###################

  trainloader:
    name: CocoLoader
    args:
      root_dir: "/content/data/flickr30k_images/flickr30k_images"
      ann_path: "/content/data/train.json"
      image_size: 224
      keep_ratio: False
      type: "train"
      batch_size: 32

  valloader:
    name: RawCocoLoader
    args:
      root_dir: "/content/data/flickr30k_images/flickr30k_images"
      ann_path: "/content/data/val.json"
      image_size: 224
      keep_ratio: False
      type: "val"
      batch_size: 32
      num_workers: 2

  #################   TRAINING CONFIG   ###################

  globals:
    gpu_devices: '0'                     # supports multi-gpus
    num_epochs: 100
    mixed_precision: False                # whether to use nvidia apex
    total_accumulate_steps: 0           # step * batch_size, not use if equal 0, gradient accumulation

  model:
    name: "SGRAF"
    args:
      d_embed: 1024                      # output_dim
      d_model: 768                       # model dim
      aggregation: "mean"               # [mean, first]
      sim_dim: 256
      sgr_step: 3


  loss:
    name: "contrastive"                # [contrastive, nxtent, custom_nxtent, triplet]
    # distance: 
    #   name: "cosine"                   # [cosine, dot, euclidean]      
    # reducer:
    #   name: "threshold"
    #   high: 0.2
    # regularizer:                     # [l1, l2, mean]
    #   name: "l2"
      
  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here