settings:
  #################   DATASET CONFIG   ###################

  project_name: "retrieval"    # also the folder name of the dataset that under ./data folder
  train_imgs: "/content/data/flickr30k_images/flickr30k_images"
  val_imgs: "/content/data/flickr30k_images/flickr30k_images"
  train_anns: "/content/data/train.json"
  val_anns: "/content/data/val.json"
  feat_dir: "/content/data/bottom_up"
  text_dir: "/content/data/bert_features"

  #################   TRAINING CONFIG   ###################
  
  text_extractor: 'distilbert-base-uncased'

  gpu_devices: '0'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 128
  num_workers: 2

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.001                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005

  lr_scheduler:
    name: "cosine2"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                        # if need to specify more scheduler arguments, do it here

  # gradient accumulation
  mixed_precision: False                # whether to use nvidia apex
  total_accumulate_steps: 0           # step * batch_size, not use if equal 0

  # Test time augmentation
  tta: False                             # whether to use TTA while validation
